external_ip_get_domain = "https://ipinfo.io/ip"
TOKEN="$TOKEN"
CHAT_ID="$CHAT_ID"
luna_addr = 'http://10.16.40.210:5000/version'
tg_url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
paths = ("/", "/home")
license_url = "http://10.16.40.222:5120/1/license"
main_db_addr="8.8.8.8"
main_db_port= 533
translator_config="config.yaml"
terminal_ips_file = "ips.txt"
disk_space_allowed_percent = 70
max_errors = 3
max_terminal_errors = 2
max_atto_socket_errors = 2
default_shutdown = 0
default_timeout = 3
sleep_time = 5
check_start_time = (7)
check_end_time = (20)
translator_port = 8005
synchronizer_port = 8001
message_type = "console" #telegram or console
